return {
  {
    "nvim-treesitter/nvim-treesitter",
    build = ":TSUpdate",
    main = "nvim-treesitter.configs",
    opts = {
      ensure_installed = {
        "lua",
        "vimdoc",
        "c",
        "cpp",
        "c_sharp",
        "rust",
        "python",
        "go",
        "json",
        "yaml",
        "toml",
        "markdown",
        "markdown_inline",
        "bash",
        "javascript",
        "typescript",
        "tsx",
        "html",
        "css",
        "regex",
      },
      auto_install = true,
      highlight = { enable = true },
      indent = { enable = true },
    },
  },
}
